[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = { version = "0.8.0" }
hdk = { version = "0.7.0" }
holochain_serialized_bytes = "0.0.57"
serde = "1"

[workspace.dependencies.ark]
path = "dnas/ark/zomes/coordinator/ark"

[workspace.dependencies.ark_integrity]
path = "dnas/ark/zomes/integrity/ark"
